### ISSUE TITLE
Stack traces logged during benign non-200 returns

### ISSUE THREAD

**Issue by kofalt** [scitran/core#202]
Stack traces catch the eye when developing or reviewing logs, and right now we sometimes dump a stack in cases that are expected and benign:

```
2016-03-16 15:53:27      scitran.api                  base.py   189:ERRO Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "./api/jobs.py", line 292, in next
    self.abort(400, 'No jobs to process')
  File "./api/base.py", line 254, in abort
    webapp2.abort(code, detail=detail, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1830, in abort
    raise cls(*args, **kwargs)
HTTPBadRequest: No jobs to process
```

This is partially blocked by #66 for the reasons mentioned in that thread, but we might be able to solve this sooner by changing our usage of `self.abort`. Filed as part of an ops conversation with @ryansanford. _Update_: @lmperry just ran into this in prod as well.

**Comment by kofalt** [comment]
Just a side note that the above stack trace is printed on (to my knowledge) every production deployment into the api log, every 5 seconds. I'd really love to get rid of this...

**Comment by lmperry** [comment]
+1 on that. It drives me just a little crazy.
