### ISSUE TITLE
As a site admin, not managing the site, requesting another user's groups and projects 403s.

### ISSUE THREAD

**Issue by mrDarcyMurphy** [scitran/core#245]
This may have been the case for some time but wasn't an issue until work began on https://github.com/flywheel-io/frontend/issues/238.

To duplicate this in the UI checkout [frontend/238-group-admin-site-mgmt-updates](https://github.com/flywheel-io/frontend/tree/238-group-admin-site-mgmt-updates) and core/master. Log in as a site admin, click the newly visible 'Site' link on the sidebar, then check your logs.

The requests work fine when appending `?root=true` but it's not being appended because the UI isn't in "Site Managing" mode. Given the sensitive nature of the data being requested I'm not sure how to proceed here. @gsfr and @elisapoquette, I'll need your input here.

**Request**

```
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:ya29..wwKXvGuDsp6GKZWBFjOBvPQRwdMj03wQVoFITTIdidK6n2KE6D07eAfIiFGgwk2Hq1A
Cache-Control:no-cache
Connection:keep-alive
Cookie:_ga=GA1.2.1432372248.1459794776
DNT:1
Host:docker.local.flywheel.io:8443
Pragma:no-cache
Referer:https://docker.local.flywheel.io:8443/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
```

**Response**

```
Cache-Control:no-cache
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json; charset=utf-8
Date:Wed, 13 Apr 2016 15:59:36 GMT
Server:nginx/1.9.3
Transfer-Encoding:chunked
Vary:Accept-Encoding
```

```
{"status_code": 403, "message": "User darcymurphy@flywheel.io may not see the Projects of User no_access@fakeuser.com"}
```

**Stacktrace**

```
uwsgi_1          | 2016-04-13 16:04:24      scitran.api                  base.py   108:DEBU looked up cached token in 0ms
uwsgi_1          | 2016-04-13 16:04:24      scitran.api                  base.py   258:DEBU from None darcymurphy@flywheel.io GET /api/users/no_access@fakeuser.com/projects {}
uwsgi_1          | 2016-04-13 16:04:24      scitran.api                  base.py   305:WARN darcymurphy@flywheel.io 403 User darcymurphy@flywheel.io may not see the Projects of User no_access@fakeuser.com
uwsgi_1          | 2016-04-13 16:04:24      scitran.api                  base.py   237:ERRO Traceback (most recent call last):
uwsgi_1          |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
uwsgi_1          |     return method(*args, **kwargs)
uwsgi_1          |   File "./api/handlers/containerhandler.py", line 249, in get_all_for_user
uwsgi_1          |     results = permchecker(self.storage.exec_op)('GET', query=query, user=user, projection=projection)
uwsgi_1          |   File "./api/auth/containerauth.py", line 106, in f
uwsgi_1          |     handler.abort(403, 'User ' + handler.uid + ' may not see the Projects of User ' + user['_id'])
uwsgi_1          |   File "./api/base.py", line 306, in abort
uwsgi_1          |     webapp2.abort(code, detail=detail, **kwargs)
uwsgi_1          |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1830, in abort
uwsgi_1          |     raise cls(*args, **kwargs)
uwsgi_1          | HTTPForbidden: User darcymurphy@flywheel.io may not see the Projects of User no_access@fakeuser.com
uwsgi_1          |
uwsgi_1          | [pid: 15|app: 0|req: 80/142] 192.168.99.1 () {50 vars in 926 bytes} [Wed Apr 13 16:04:24 2016] GET /api/users/no_access@fakeuser.com/projects => generated 119 bytes in 6 msecs (HTTP/1.1 403) 3 headers in 119 bytes (2 switches on core 0)
uwsgi_1          | 2016-04-13 16:04:24      scitran.api                  base.py   108:DEBU looked up cached token in 0ms
uwsgi_1          | 2016-04-13 16:04:24      scitran.api                  base.py   258:DEBU from None darcymurphy@flywheel.io GET /api/users/no_access@fakeuser.com/groups {}
uwsgi_1          | 2016-04-13 16:04:24      scitran.api                  base.py   305:WARN darcymurphy@flywheel.io 403 User darcymurphy@flywheel.io may not see the Groups of User no_access@fakeuser.com
uwsgi_1          | 2016-04-13 16:04:24      scitran.api                  base.py   237:ERRO Traceback (most recent call last):
uwsgi_1          |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
uwsgi_1          |     return method(*args, **kwargs)
uwsgi_1          |   File "./api/handlers/grouphandler.py", line 48, in get_all
uwsgi_1          |     results = permchecker(self.storage.exec_op)('GET', projection=projection)
uwsgi_1          |   File "./api/auth/groupauth.py", line 29, in f
uwsgi_1          |     handler.abort(403, 'User ' + handler.uid + ' may not see the Groups of User ' + uid)
uwsgi_1          |   File "./api/base.py", line 306, in abort
uwsgi_1          |     webapp2.abort(code, detail=detail, **kwargs)
uwsgi_1          |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1830, in abort
uwsgi_1          |     raise cls(*args, **kwargs)
uwsgi_1          | HTTPForbidden: User darcymurphy@flywheel.io may not see the Groups of User no_access@fakeuser.com
uwsgi_1          |
uwsgi_1          | [pid: 15|app: 0|req: 81/143] 192.168.99.1 () {50 vars in 922 bytes} [Wed Apr 13 16:04:24 2016] GET /api/users/no_access@fakeuser.com/groups => generated 117 bytes in 6 msecs (HTTP/1.1 403) 3 headers in 119 bytes (2 switches on core 1)
```

**Comment by gsfr** [comment]
Hmm. Looking at flywheel-io/frontend#238, I don't understand the use case for why one user needs to know another user's groups and projects. I don't think that info should be given out to non-site admins. Please explain.

**Comment by elisapoquette** [comment]
The original ticket was to allow group admins who were not site admins access group management functionality. Right now, all group admins must also be site admins in order to manage group permissions. @gsfr can you work with @mrDarcyMurphy to figure this out?

**Comment by mrDarcyMurphy** [comment]
@gsfr There isn't a "need," that's simply how the page works. Before this week no one could get to that page unless they were both a site admin _and_ in management mode. As I said…

> Given the sensitive nature of the data being requested I'm not sure how to proceed here.

What I'm trying to ask is:

1. Is this the right behavior for the API?
2. If so, how should the UI handle this situation?
3. If not, then please expose the necessary data via the API.

Keeping the restriction on the API may be the right choice because I agree that a non-admin user doesn't need that data. That would then lead us towards option 2, but I need to be sure.

**Comment by mrDarcyMurphy** [comment]
I think I've found a way to work around this for now.
