### ISSUE TITLE
Group Admins can't add, edit, or remove Tags on Groups.

### ISSUE THREAD

**Issue by mrDarcyMurphy** [scitran/core#260]
This only applies to users who are group admins but aren't site admins. I _think_ users with read/write access need this functionality as well but I'm not 100% sure.

Here's a stack trace when trying to add a tag.

```
uwsgi_1          | 2016-04-22 18:09:21      scitran.api                  base.py   108:DEBU looked up cached token in 0ms
uwsgi_1          | 2016-04-22 18:09:21      scitran.api                  base.py   258:DEBU from None darcymurphy@invenshure.com POST /api/groups/admin/tags {}
uwsgi_1          | 2016-04-22 18:09:21      scitran.api            validators.py   135:DEBU {u'additionalProperties': False, u'$schema': u'http://json-schema.org/draft-04/schema#', u'type': u'object', u'properties': {u'value': {u'type': u'string'}}}
uwsgi_1          | 2016-04-22 18:09:21      scitran.api            validators.py    84:DEBU {u'value': u'foobar'}
uwsgi_1          | 2016-04-22 18:09:21      scitran.api                  base.py   305:WARN darcymurphy@invenshure.com 403 user not authorized to perform a POST operation on the list
uwsgi_1          | 2016-04-22 18:09:21      scitran.api                  base.py   237:ERRO Traceback (most recent call last):
uwsgi_1          |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
uwsgi_1          |     return method(*args, **kwargs)
uwsgi_1          |   File "./api/handlers/listhandler.py", line 134, in post
uwsgi_1          |     result = keycheck(mongo_validator(permchecker(storage.exec_op)))('POST', _id=_id, payload=payload)
uwsgi_1          |   File "./api/validators.py", line 95, in validator
uwsgi_1          |     return exec_op(method, **kwargs)
uwsgi_1          |   File "./api/auth/listauth.py", line 67, in f
uwsgi_1          |     handler.abort(403, 'user not authorized to perform a {} operation on the list'.format(method))
uwsgi_1          |   File "./api/base.py", line 306, in abort
uwsgi_1          |     webapp2.abort(code, detail=detail, **kwargs)
uwsgi_1          |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1830, in abort
uwsgi_1          |     raise cls(*args, **kwargs)
uwsgi_1          | HTTPForbidden: user not authorized to perform a POST operation on the list
uwsgi_1          |
uwsgi_1          | [pid: 17|app: 0|req: 548/1019] 192.168.99.1 () {56 vars in 1041 bytes} [Fri Apr 22 18:09:21 2016] POST /api/groups/admin/tags => generated 94 bytes in 18 msecs (HTTP/1.1 403) 3 headers in 118 bytes (2 switches on core 0)
```

**Comment by nagem** [comment]
@elisapoquette what do you think about giving users with write access to a group the ability to create/update/delete group tags?

**Comment by nagem** [comment]
The other bug was we had a mongo projection for `permissions` but not `roles` (the name for the field in groups), so the user was never found in the `roles` list.

**Comment by nagem** [comment]
Talking with Elisa, users with write access and above should be able to PUT/POST/DELETE tags.
