### ISSUE TITLE
Adding a user that already exists results in HTTP 500

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#303]
Appropriate function `UserHandler.post()` should have routing pydocs when resolving with expected response when user is created vs. already exists.

Might be related to #66 ?

```
uwsgi_1           | 2016-05-17 13:11:10      scitran.api                  base.py   270:DEBU from None None POST /api/users {}
uwsgi_1           | 2016-05-17 13:11:10      scitran.api            validators.py    84:DEBU {u'firstname': u'No', 'created': datetime.datetime(2016, 5, 17, 13, 11, 10, 862316), u'lastname': u'Access', 'modified': datetime.datetime(2016, 5, 17, 13, 11, 10, 862316), 'avatars': {}, u'_id': u'no_access@fakeuser.com', u'root': False, 'email': u'no_access@fakeuser.com'}
uwsgi_1           | 2016-05-17 13:11:10      scitran.api      containerstorage.py    51:DEBU {u'firstname': u'No', 'created': datetime.datetime(2016, 5, 17, 13, 11, 10, 862316), u'lastname': u'Access', 'modified': datetime.datetime(2016, 5, 17, 13, 11, 10, 862316), 'avatars': {}, u'_id': u'no_access@fakeuser.com', u'root': False, 'email': u'no_access@fakeuser.com'}
uwsgi_1           | 2016-05-17 13:11:10      scitran.api                  base.py   261:ERRO Traceback (most recent call last):
uwsgi_1           |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
uwsgi_1           |     return method(*args, **kwargs)
uwsgi_1           |   File "./api/handlers/userhandler.py", line 159, in post
uwsgi_1           |     result = mongo_validator(permchecker(self.storage.exec_op))('POST', payload=payload)
uwsgi_1           |   File "./api/validators.py", line 95, in validator
uwsgi_1           |     return exec_op(method, **kwargs)
uwsgi_1           |   File "./api/auth/userauth.py", line 28, in f
uwsgi_1           |     return exec_op(method, _id=_id, query=query, payload=payload, projection=projection)
uwsgi_1           |   File "./api/dao/containerstorage.py", line 47, in exec_op
uwsgi_1           |     return self._create_el(payload)
uwsgi_1           |   File "./api/dao/containerstorage.py", line 52, in _create_el
uwsgi_1           |     return self.dbc.insert_one(payload)
uwsgi_1           |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 625, in insert_one
uwsgi_1           |     bypass_doc_val=bypass_document_validation),
uwsgi_1           |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 530, in _insert
uwsgi_1           |     check_keys, manipulate, write_concern, op_id, bypass_doc_val)
uwsgi_1           |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 513, in _insert_one
uwsgi_1           |     _check_write_command_response([(0, result)])
uwsgi_1           |   File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 300, in _check_write_command_response
uwsgi_1           |     raise DuplicateKeyError(error.get("errmsg"), 11000, error)
uwsgi_1           | DuplicateKeyError: E11000 duplicate key error index: scitran.users.$_id_ dup key: { : "no_access@fakeuser.com" }
uwsgi_1           | 
uwsgi_1           | [pid: 32|app: 0|req: 104/237] 172.17.0.9 () {40 vars in 518 bytes} [Tue May 17 13:11:10 2016] POST /api/users => generated 130 bytes in 12 msecs (HTTP/1.1 500) 3 headers in 131 bytes (2 switches on core 1)

```

**Comment by kofalt** [comment]
Yeah, definitely (relates to | is blocked by) #66.
There are likely several error states that will have the wrong code until that is resolved.
