### ISSUE TITLE
ListHandler uses kwargs in place of query params

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#534]
See this line of ListHandler.get, where the "query_params" argument to the validation function is set to "kwargs" instead of request.GET

https://github.com/scitran/core/blob/master/api/handlers/listhandler.py#L130

Example API call:

curl -k -H "Authorization: scitran-user xxx" https://docker.local.flywheel.io:8443/api/groups/scitran/roles?_id=scitran

Example response:

``` json
{"status_code": 500, "message": "
    []
    is different from expected:
    [u_id, usite]
    "}
```

Traceback:

```
uwsgi_1           | 2016-10-10 20:01:51      scitran.api                  base.py   288:ERRO Traceback (most recent call last):
uwsgi_1           |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
uwsgi_1           |     return method(*args, **kwargs)
uwsgi_1           |   File "./api/handlers/listhandler.py", line 130, in get
uwsgi_1           |     result = keycheck(permchecker(storage.exec_op))('GET', _id, query_params=kwargs)
uwsgi_1           |   File "./api/validators.py", line 123, in f
uwsgi_1           |     _check_query_params(schema.get('key_fields'), query_params)
uwsgi_1           |   File "./api/validators.py", line 152, in _check_query_params
uwsgi_1           |     """.format(query_params.keys(), keys)
uwsgi_1           | AssertionError:
uwsgi_1           |     []
uwsgi_1           |     is different from expected:
uwsgi_1           |     [u'_id', u'site']
uwsgi_1           |
uwsgi_1           |  request_id=e10c54ff-1476129711
uwsgi_1           | [pid: 19|app: 0|req: 55/64] 192.168.99.1 () {34 vars in 495 bytes} [Mon Oct 10 20:01:51 2016] GET /api/groups/scitran/roles?_id=scitran => generated 105 bytes in 8 msecs (HTTP/1.1 500) 3 headers in 131 bytes (2 switches on core 0)
```

**Comment by coltonlw** [comment]
We will have to leave this behavior as-is, because routes use uri parameters in place of query parameters and depend on "query_params" argument being set to "kwargs" of the handler method.  Suggest properly restricting methods for those routes which do not have the appropriate uri parameters, such as #535

**Comment by coltonlw** [comment]
@nagem Let me know what you think, if we are going to leave the existing behavior per my previous comment
