### ISSUE TITLE
Not including ticket query param for files endpoints causes 500

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#584]
GET /{ContainerName}/{ContainerId}/analyses/{AnalysisId}/files

If "ticket" query param is included and not empty, download files.
If "ticket" query param is included and empty, create a ticket for all files in the anlaysis
If no "ticket" query param is included, server error 500

```python
2016-10-31 19:48:42      scitran.api                  base.py   288:ERRO Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "./api/handlers/listhandler.py", line 817, in download
    self._send_batch(ticket)
UnboundLocalError: local variable 'ticket' referenced before assignment
```

**Comment by nagem** [comment]
@ambrussimon-invenshure fixed this issue while writing tests (thanks ambrus!)
