### ISSUE TITLE
User sometimes gets unusual 500 error after initial request when "logging in" on frontend

### ISSUE THREAD

**Issue by nagem** [scitran/core#607]
This is not easy to reproduce, and is confusing as the only db call to the `authtokens` collection is a `replace_one` call with `upsert=true`.
```
Traceback (most recent call last):
  File "./api/api.py", line 217, in dispatcher
    rv = router.default_dispatcher(request, response)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1101, in __call__
    handler = self.handler(request, response)
  File "./api/handlers/containerhandler.py", line 82, in __init__
    super(ContainerHandler, self).__init__(request, response)
  File "./api/base.py", line 52, in __init__
    self.uid = self.authenticate_user(access_token)
  File "./api/base.py", line 141, in authenticate_user
    config.db.authtokens.replace_one({'_id': access_token}, update, upsert=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 785, in replace_one
    bypass_doc_val=bypass_document_validation)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 710, in _update
    _check_write_command_response([(0, result)])
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 300, in _check_write_command_response
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
DuplicateKeyError: E11000 duplicate key error collection: scitran.authtokens index: _id_ dup key: { : "<google auth token>" }
```

**Comment by nagem** [comment]
Fixed in #652
