### ISSUE TITLE
Unable to register flywheel exchange gear when prefetching enabled

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#612]
**Error**
```
2016-12-07 13:59:43      scitran.api                  base.py   305:ERRO Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "./api/jobs/handlers.py", line 78, in post
    upsert_gear(self.request.json)
  File "./api/jobs/gears.py", line 113, in upsert_gear
    insert_gear(doc)
  File "./api/jobs/gears.py", line 86, in insert_gear
    log.info('Queuing prefetch job for gear ' + doc['name'])
KeyError: 'name'
 request_id=1b6ff0f8-1481119183
[pid: 22|app: 0|req: 2/4] 172.20.0.11 () {40 vars in 546 bytes} [Wed Dec  7 13:59:43 2016] POST /api/gears/dcm2niix => generated 41 bytes in 43 msecs (HTTP/1.1 500) 3 headers in 130 bytes (2 switches on core 1)


```

**Comment by ryansanford** [comment]
@kofalt 
Can you check for any similar cases that may be lurking?
